[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "prioritary-mvlm"
version = "0.1.0"
description = "Prioritary MVLM training utilities"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "torch",
    "transformers",
]
